# Generated by Django 3.1.7 on 2021-06-19 19:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Combo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Order date')),
                ('drink', models.CharField(choices=[('T', 'Tea'), ('C', 'Coffee'), ('W', 'Water')], default='W', max_length=1)),
                ('cake', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.cake')),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
    ]
