# Generated by Django 3.1.7 on 2021-06-20 21:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_auto_20210620_2027'),
    ]

    operations = [
        migrations.AddField(
            model_name='cake',
            name='toppings',
            field=models.ManyToManyField(to='main_app.Topping'),
        ),
    ]
